[package]
name = "irmaseal-core"
description = "Core library for IRMAseal communication and bytestream operations."
version = "0.1.3"
authors = ["Wouter Geraedts <git@woutergeraedts.nl>"]
edition = "2018"
license = "MIT"
keywords = ["ibe", "encryption", "ecc", "no_std"]
homepage = "https://github.com/Wassasin/irmaseal/tree/master/irmaseal-core"
categories = ["cryptography", "no-std"]

[dependencies]
aes = { version = "0.7.0", optional = true }
ctr = { version = "0.7.0", optional = true }
digest = { version = "0.8.1" }
rand = { version = "0.8.4" }
sha3 = { version = "0.8.2" }
arrayref = "0.3.5"
arrayvec = { version = "0.7.1", features = ["serde"] }
subtle = "2.3"
postcard = "0.7.2"
ibe = { git = "https://github.com/encryption4all/ibe.git", branch = "features_and_docs", features = ["cgwfo"] }
serde = { version = "1.0.126", features = ["derive"] }
serde-big-array = { version = "0.3.2", features = ["const-generics"] }
rmp-serde = "0.15.5"
serde_json = "1.0.68"
tiny-keccak = { version = "2.0.2", features = ["sha3"] }
base64ct = { version = "1.0.2" }

[dev-dependencies]
serde-transcode = "1.1.1"

[features]
stream = ["aes", "ctr"]
v1 = ["ibe/kv1"]
