[package]
name = "irmaseal-core"
description = "Core library for IRMAseal communication and bytestream operations."
version = "0.1.2"
authors = ["Wouter Geraedts <git@woutergeraedts.nl>"]
edition = "2018"
license = "MIT"
keywords = ["ibe", "encryption", "ecc", "no_std"]
homepage = "https://github.com/Wassasin/irmaseal/tree/master/irmaseal-core"
categories = ["cryptography", "no-std"]

[dependencies]
digest = { version = "0.8", optional = true }
rand = { version = "0.7", optional = true }
aes = { version = "0.3", optional = true }
cfb-mode = { version = "0.3", optional = true }
hmac = { version = "0.7", optional = true }
sha3 = { version = "0.8", optional = true }

arrayref = "0.3"
arrayvec = { version = "0.5", features = ["array-sizes-129-255", "serde"] }
subtle = "2.3"
serde = { version = "1.0", features = ["derive"] }
base64 = "0.12"
ibe = "0.1"

[features]
default = ["stream"]

stream = ["digest", "rand", "aes", "cfb-mode", "hmac", "sha3"]
