[package]
name = "irmaseal-core"
description = "Core library for IRMAseal communication and bytestream operations."
version = "0.1.3"
authors = ["Wouter Geraedts <git@woutergeraedts.nl>"]
edition = "2018"
license = "MIT"
keywords = ["ibe", "encryption", "ecc", "no_std"]
homepage = "https://github.com/Wassasin/irmaseal/tree/master/irmaseal-core"
categories = ["cryptography", "no-std"]

[dependencies]
rand = { version = "0.8.4" }
subtle = "2.3"
base64 = "0.12"
ibe = { git = "https://github.com/encryption4all/ibe.git", branch = "features_and_docs", features = [
  "cgwfo"
] }
serde = { version = "1.0.126", features = ["derive"] }
serde-big-array = { version = "0.3.2", features = ["const-generics"] }
rmp-serde = "0.15.5"
serde_json = "1.0.68"
tiny-keccak = { version = "2.0.2", features = ["sha3"] }
futures = { version = "0.3.17" }
async-trait = "0.1.51"
# For normal stream feature
aes = { version = "0.7.0", optional = true }
ctr = { version = "0.7.0", optional = true }
# For wasm_stream feature
wasm-bindgen = { version = "0.2.78", optional = true }
js-sys = { version = "0.3.55", optional = true }
cipher = { version = "0.3.0", optional = true }
wasm-bindgen-futures = { version = "0.4.28", optional = true }
web-sys = { version = "0.3.55", features = [
  "SubtleCrypto",
  "AesCtrParams",
  "Crypto",
  "CryptoKey"
], optional = true }

[dev-dependencies]
serde-transcode = "1.1.1"
criterion = "0.3.5"

[features]
default = []
stream = ["aes", "ctr", "tiny-keccak/kmac"]
wasm_stream = [
  "cipher",
  "tiny-keccak/kmac",
  "wasm-bindgen",
  "js-sys",
  "wasm-bindgen-futures",
  "web-sys/SubtleCrypto",
  "web-sys/AesCtrParams",
  "web-sys/Crypto",
  "web-sys/CryptoKey"
]
v1 = ["ibe/kv1"]

[[bench]]
name = "main"
harness = false
required-features = ["stream"]
