[package]
name = "irmaseal-cli"
description = "Commandline interface for IRMAseal"
version = "0.1.3"
authors = ["Wouter Geraedts <git@woutergeraedts.nl>"]
edition = "2018"
license = "MIT"

[dependencies]
irmaseal-core = "0.1"
ibe = "0.1"

tokio = { version = "0.2", features = ["rt-threaded", "time"] }
futures = "0.3"
qrcode = { version = "0.12", default-features = false }
clap = { version = "2.33", features = ["yaml"] }
rand = "0.7"
arrayvec = { version = "0.5", features = ["array-sizes-129-255"] }
serde = "1.0"
reqwest = { version = "0.10", features = ["rustls-tls", "json"], default-features = false }
