[package]
authors = ["Wouter Geraedts <git@woutergeraedts.nl>"]
edition = "2018"
license = "MIT"
name = "irmaseal-pkg"
version = "0.1.2"

[dependencies]
actix-cors = "0.1.0"
actix-rt = "0.2.2"
arrayref = "0.3.5"
clap = { version = "3.0.0-beta.4", features = ["derive"] }
futures = "0.1.28"
irma = "0.0"
paste = "1.0.5"
rand = "0.8.4"
serde = "*"
serde_json = "1.0.68"
subtle = "2.1.1"

[dependencies.actix-web]
default-features = false
version = "1.0.7"

[dependencies.ibe]
features = ["cgwfo"]
path = "../../ibe"

[dependencies.irmaseal-core]
path = "../irmaseal-core"

[features]
v1 = ["irmaseal-core/v1", "ibe/kv1"]
