[package]
name = "irmaseal-pkg"
version = "0.1.2"
authors = ["Wouter Geraedts <git@woutergeraedts.nl>"]
edition = "2018"
license = "MIT"

[dependencies]
irmaseal-core = "0.1"
ibe = "0.1"
irma = "0.0"

actix-rt = "0.2"
actix-web = { version = "1.0", default-features = false }
arrayref = "0.3"
subtle = "2.3"
clap = { version = "2.33", features = ["yaml"] }
rand = "0.7"
serde_json = "1.0"
futures = "0.1"
