[package]
authors = ["Wouter Geraedts <git@woutergeraedts.nl>"]
edition = "2018"
license = "MIT"
name = "irmaseal-pkg"
version = "0.1.2"

[dependencies]
actix-rt = "2.3.0"
actix-web = { version = "3.3.2", default-features = false }
actix-cors = "0.5.4"
arrayref = "0.3.5"
clap = { version = "3.0.0-beta.4", features = ["derive"] }
futures = { version = "0.3", default-features = false }
irma = "0.0"
paste = "1.0.5"
rand = "0.8.4"
serde = "*"
serde_json = "1.0.68"
subtle = "2.1.1"

[dependencies.ibe]
features = ["cgwfo"]
path = "../../ibe"

[dependencies.irmaseal-core]
path = "../irmaseal-core"

[features]
v1 = ["irmaseal-core/v1", "ibe/kv1"]
