on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Continuous integration

jobs:
  test:
    name: Test workspaces
    strategy:
      matrix:
        workspace: [core, pkg, cli]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          args: --manifest-path irmaseal-${{ matrix.workspace }}/Cargo.toml --all-features
          command: test

  format:
    name: Format workspaces
    strategy:
      matrix:
        workspace: [core, pkg, cli]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          args: --manifest-path irmaseal-${{ matrix.workspace }}/Cargo.toml --all -- --check
          command: fmt

  test-wasm-browsers:
    name: Run wasm tests in browsers
    strategy:
      matrix:
        browser: [chrome, firefox]
        os: [ubuntu-latest]
        include:
          - browser: safari
            os: macos-latest
    runs-on: ${{ matrix.os }} 
    env:
      WASM_BINDGEN_TEST_TIMEOUT: 120
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - if: ${{ matrix.firefox }}
        run: sudo apt update && sudo apt install firefox
      - run: wasm-pack test --headless --${{ matrix.browser }} ./irmaseal-wasm-bindings
